### ISSUE TITLE
Unify variables

### ISSUE THREAD

**Issue by avalor1** [T-Systems-MMS/ansible-collection-acme#44]
The naming of variables is not consistent. Some contain the name of the role and some do not. Some variables could also be already used in context of other roles (`dns_user` `dns_password` ).

I think we should unify the variable names coresponding to the rolename. 
E.g. `acme_collection_dns_user` `acme_collection_dns_password` `acme_collection_conf_dir` ...

Maybe this could be done together with the renaming of the role in #43 

What do you think?

**Comment by schurzi** [comment]
Scoping our variables is a good idea. i would leave out the `collection` from the name. I think `acme_...` is specific enough.

Also as you stated, this is a thing for a 2.0.0 release, since it will break all configurations.
