### ISSUE TITLE
Use temp-dir for creation of certificates?

### ISSUE THREAD

**Issue by rndmh3ro** [T-Systems-MMS/ansible-collection-acme#5]
Right now the home-directory is used for storage of the certificates: https://github.com/T-Systems-MMS/ansible-collection-letsencrypt/blob/001b54862ce6ec34258cd019479e59c8e4c4a370/roles/letsencrypt/defaults/main.yml#L8

```
letsencrypt_conf_dir: "{{ lookup('env','HOME') }}/letsencrypt"
letsencrypt_cert_dir: "{{ letsencrypt_conf_dir }}/certs"
```

Since people may not like (I don't) polluting their home-directory, I suggest we create and use a temporary directory to store the files in: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/tempfile_module.html

What do you think?

**Comment by avalor1** [comment]
I'am also not happy with the current solution. 
Does this temp directory persist restarts or does it get deleted after a successfull run? Asking because the account key should be persistant.
Documentation does not exactly tell if it is deleted or not but i asume it is persistant.

I think your suggestion would be a good solution for this. Will add it

**Comment by rndmh3ro** [comment]
Well, as the name implies, a *temp*dir is not persisent. Are you sure that the account key needs to be persistent?

**Comment by schurzi** [comment]
I read up on this a few weeks ago. Historically they planned the accout_key as somethin importatnt to keep and to trigger things like revocation. But this was never implemented and now it is optional to keep the account_key.

see: https://community.letsencrypt.org/t/why-backup-my-account-key/104761

**Comment by avalor1** [comment]
I also found this one and i agree that it is not necessary in most circumstances but this also means that you would create a new account at least every 90 days for n certificates 🤔 If you have more than 10 customers for which you want to automatically create certficates and trigger this via a cron at the same time you would hit the rate limit relatively fast. 

I think we will not hit the rate limit and it should be okay for the first implementation but i can imagine that some people would use it at a larger scale
(https://letsencrypt.org/docs/rate-limits/)

**Comment by avalor1** [comment]
Maybe we should make it a choice. I can see some situations where a persistent directory would be good

**Comment by rndmh3ro** [comment]
You can use a persistent directory, but default to `/tmp` so it does not interfere with other stuff from the user.
