### ISSUE TITLE
Requirements missing

### ISSUE THREAD

**Issue by michaelamattes** [T-Systems-MMS/ansible-collection-acme#50]
Requirements definition missing e.g. needed pip install versions

**Comment by avalor1** [comment]
Hi,

thanks for raising this issue. Could you please elaborate a little further what you are missing and which packages you had to install?

**Comment by michaelamattes** [comment]
Hi,

if ansible is not installed in the latest version over pip then cryptography had to be update to version >3.4.

**Comment by rndmh3ro** [comment]
@michaelamattes what should we do here?

**Comment by avalor1** [comment]
I am closing this issues as their was no response for nearly a year.
