### ISSUE TITLE
Test collection with other acme providers

### ISSUE THREAD

**Issue by rndmh3ro** [T-Systems-MMS/ansible-collection-acme#55]
There are other acme providers besides Lets Encrypt:
* https://zerossl.com/
* https://www.buypass.com/ssl/products/acme

We should check if we support these providers, too.
Maybe integrate a (manual) test.

**Comment by avalor1** [comment]
I checked both of the mentioned sites. As for zerossl I think this wouldn't be a good addtion. buypass.com could be possible but has two main limitations (see list).

zerossl:
- no mention of max domains per certificate
- there do not seems to be the posibility of wildcard certificates
- it seems that there are a max of 3 certificates before you have to pay
- reviews are not very promising (https://www.trustpilot.com/review/zerossl.com)

buypass.com:
- 5 domains per certificate
- no wildcard certificates

I also found https://www.sslforfree.com/ but I'm not sure if the just use the zerossl servers or does have their own infrastructure.

Of course there are more providers which offer acme automation but would come with a cost. Not sure if we should implement something like that.

**Comment by rndmh3ro** [comment]
Thanks for checking this!

I'd say we stick to Let's Encrypt for now. If someone wants to use other providers, they are free to do so and tell us.
