### ISSUE TITLE
[Question] why new versions are not supportet?

### ISSUE THREAD

**Issue by MMS-CoC09** [T-Systems-MMS/ansible-collection-acme#85]
### Question

hello,

if i would like to use your collection i became the following error:

```
failed: [localhost] (item=*.example.org) => {"ansible_loop_var": "item", "changed": false, "item": "*.example.org", "msg": "Incompatible openstacksdk library found: Version MUST be >=0.36 and <=0.98.999, but 0.103.0 is larger than maximum version 0.98.999."}
```

Why newer version are not supported?

**Comment by avalor1** [comment]
Hi @MMS-CoC09 , it seems that there is a problem with your ansible version and openstack modules. Please make sure that your ansible version and the openstack sdk you are using are compatible. Otherwise i do not see any reason why the collection/role should not work

**Comment by avalor1** [comment]
Closing this as no further question came in.
